<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>FunctionalGasStove</AssemblyName>
    <RootNamespace>FunctionalGasStove</RootNamespace>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Game7D2D)' == ''">
    <Game7D2D>$(MSBuildThisFileDirectory)..</Game7D2D>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(Game7D2D)/7DaysToDie_Data/Managed/Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(Game7D2D)/Mods/0_TFP_Harmony/0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="LogLibrary">
      <HintPath>$(Game7D2D)/7DaysToDie_Data/Managed/LogLibrary.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="All" />
  </ItemGroup>
</Project>
